const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),ts=require('typescript');
function setup(fetcher=async()=>new Response('{}',{status:503})){
 const storage=()=>{const map=new Map();return{getItem:key=>map.get(key)||null,setItem:(key,value)=>map.set(key,String(value)),removeItem:key=>map.delete(key)}};
 const localStorage=storage(),sessionStorage=storage();const cache={};let now=Date.now();class Clock extends Date{static now(){return now;}}
 const globals={exports:{},window:{},localStorage,sessionStorage,navigator:{},fetch:fetcher,Response,Date:Clock,atob};
 function load(name){if(cache[name])return cache[name];const exports={};cache[name]=exports;vm.runInNewContext(ts.transpileModule(fs.readFileSync(`src/lib/${name}.ts`,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{...globals,exports,require:p=>load(p.replace('./',''))});return exports;}
 const offline=load('offlineAuth'),session=load('session');const token='x.'+Buffer.from(JSON.stringify({sub:'user-a',org:'org-a'})).toString('base64url')+'.x';
 const trust=()=>offline.rememberVerifiedSession({id:'user-a'}, {roles:['Worker'],permissions:['assets.read'],is_superuser:false},token,true);
 return {offline,session,localStorage,sessionStorage,token,trust,advance:ms=>now+=ms};
}
test('trusted offline access expires after 30 days and cannot renew itself',()=>{const x=setup();x.trust();assert.equal(x.offline.enterOfflineAccess(),true);const expiry=x.offline.readTrustedSession().expiresAt;x.advance(86400000);x.offline.enterOfflineAccess();assert.equal(x.offline.readTrustedSession().expiresAt,expiry);x.advance(28*86400000);assert.ok(x.offline.readTrustedSession());x.advance(86400000-1);assert.ok(x.offline.readTrustedSession());x.advance(1);assert.equal(x.offline.readTrustedSession(),null);assert.equal(x.offline.offlineAccessActive(),false);});
test('explicit lock prevents offline reopening without deleting unrelated drafts',()=>{const x=setup();x.trust();x.localStorage.setItem('draft','keep');x.offline.enterOfflineAccess();x.offline.lockOfflineAccess();assert.equal(x.offline.enterOfflineAccess(),false);assert.equal(x.localStorage.getItem('draft'),'keep');});
test('another account cannot be stored under a mismatched token',()=>{const x=setup();x.offline.rememberVerifiedSession({id:'other'},{roles:[],permissions:[],is_superuser:true},x.token,true);assert.equal(x.offline.readTrustedSession(),null);});
test('temporary and malformed refresh responses preserve tokens and trusted access',async()=>{for(const fetcher of [async()=>new Response('{}',{status:503}),async()=>new Response('not json'),async()=>{throw Error('network')}]){const x=setup(fetcher);x.trust();x.session.setTokens(x.token,'refresh',true);await assert.rejects(x.session.refreshSession('',x.token),/retry/);assert.equal(x.session.getRefreshToken(),'refresh');assert.ok(x.offline.readTrustedSession());}});
test('server rejection locks trusted access and removes rejected tokens',async()=>{const x=setup(async()=>new Response('{}',{status:401}));x.trust();x.session.setTokens(x.token,'refresh',true);assert.equal(await x.session.refreshSession('',x.token),false);assert.equal(x.offline.readTrustedSession(),null);assert.equal(x.session.getRefreshToken(),null);});
test('session-only trust is not stored persistently',()=>{const x=setup();x.offline.rememberVerifiedSession({id:'user-a'},{roles:[],permissions:[],is_superuser:false},x.token,false);assert.equal(x.localStorage.getItem('cestos_trusted_offline_session'),null);assert.ok(x.sessionStorage.getItem('cestos_trusted_offline_session'));});
test('offline queue excludes destructive and security-sensitive operations',()=>{const {offline}=setup();assert.equal(offline.offlineWriteAllowed('/api/v1/assets/rig/logs','POST'),true);for(const [path,method] of [['/api/v1/users','POST'],['/api/v1/workbook-shares','POST'],['/api/v1/payroll','PATCH'],['/api/v1/assets/rig','DELETE'],['/api/v1/tasks/1/approve','POST']])assert.equal(offline.offlineWriteAllowed(path,method),false);});

test('existing seven-day trust remains valid without offline renewal',()=>{const x=setup();x.trust();const key='cestos_trusted_offline_session';const saved=JSON.parse(x.localStorage.getItem(key));saved.expiresAt=saved.verifiedAt+7*86400000;x.localStorage.setItem(key,JSON.stringify(saved));assert.equal(x.offline.enterOfflineAccess(),true);assert.equal(x.offline.readTrustedSession().expiresAt,saved.expiresAt);x.advance(7*86400000);assert.equal(x.offline.readTrustedSession(),null);});
