const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(name){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Date,structuredClone,require:n=>load(n.replace('./',''))});return exports;}
const api=load('workbookMappingAssistant');const sheet=(rows=4,cols=2)=>({id:'s',name:'Sheet',cells:Array.from({length:rows},(_,r)=>Array.from({length:cols},(_,c)=>`${r}:${c}`)),widths:Array(cols).fill(100),heights:Array(rows).fill(30),merges:[],formats:{}});
const table={id:'/api/v1/assets',columns:[{name:'name'},{name:'hours'}]};
const proposal=()=>({mode:'rows',headerRows:[0],labelColumn:0,start:1,end:3,blockSize:1,exclude:[],fields:[{field:'name',kind:'column',r:0,c:0,confidence:'high',reason:'Name header'},{field:'hours',kind:'column',r:0,c:1,confidence:'low',reason:'Ambiguous hours'}],summary:'Table',warnings:[]});
test('large samples stay bounded and include early and final rows and distant columns',()=>{const s=sheet(2000,100),sample=api.mappingSample(s);assert.ok(sample.cells.length<=1200);assert.ok(sample.cells.some(c=>c.r===0));assert.ok(sample.cells.some(c=>c.r===1999));assert.ok(sample.cells.some(c=>c.c===99));assert.equal(sample.sampled,true);assert.equal(sample.rowCount,2000);});
test('samples omit original file and private connection metadata and truncate cell text',()=>{const s=sheet();s.source={base64:'secret'};s.connection={table:'secret'};s.cells[0][0]='x'.repeat(200);const sample=api.mappingSample(s);assert.equal(sample.cells[0].text.length,160);assert.equal(sample.source,undefined);assert.equal(sample.connection,undefined);assert.equal(sample.sampled,true);s.previewLimited=true;assert.throws(()=>api.mappingSample(s),/Fully load/);});
test('accepting selected suggestions creates a layout without mutating the sheet',()=>{const s=sheet(),p=proposal(),before=JSON.stringify(s);const l=api.proposalLayout(s,table,p,['name']);assert.deepEqual(Object.keys(l.fields),['name']);assert.equal(l.fields.name.c,0);assert.equal(JSON.stringify(s),before);assert.equal(l.validatedAt,undefined);});
test('unknown fields, duplicates and invalid coordinates are rejected',()=>{const s=sheet();for(const alter of [p=>p.fields[0].field='secret',p=>p.fields.push(p.fields[0]),p=>p.fields[0].c=99,p=>p.mode='invalid']){const p=proposal();alter(p);assert.throws(()=>api.proposalLayout(s,table,p,['name','hours']));}});
test('filling gaps requires the same record layout and bounds',()=>{const a=api.proposalLayout(sheet(),table,proposal(),['name']),b=api.proposalLayout(sheet(),table,proposal(),['hours']);assert.equal(api.compatibleLayout(a,b),true);assert.equal(api.compatibleLayout(a,{...b,start:2}),false);});
