const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(name){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>load(n.replace('./','')),Date});return exports;}
const formula=load('workbookFormulas'),op=load('workbookOperations');
const sheet=cells=>({id:'s',name:'Data',cells,widths:cells[0].map(()=>120),heights:cells.map(()=>30),merges:[],formats:{}});
test('formulas evaluate totals, references, arithmetic and overnight hours',()=>{const s=sheet([['2','4','=SUM(A1:B1)','=AVERAGE(A1:B1)'],['22:00','06:30','=HOURS(A2,B2)','=MOD(B2-A2,1)*24']]);assert.deepEqual(JSON.parse(JSON.stringify(formula.calculateSheet(s))),[['2','4','6','3'],['22:00','06:30','8.5','8.5']]);});
test('formula errors do not crash other cells and cycles are detected',()=>{const v=formula.calculateSheet(sheet([['=B1','=A1','=1/0','=FOO(1)','=Z99','=2+3*4']]));assert.deepEqual(Array.from(v[0]),['#CYCLE!','#CYCLE!','#DIV/0!','#NAME?','#REF!','14']);});
test('formula filling respects mixed absolute anchors and deleted references',()=>{assert.equal(formula.translateFormula('=$A1+B$2+$C$3',2,1),'=$A3+C$2+$C$3');assert.equal(formula.translateFormula('=A1',-1,0),'=#REF!');assert.equal(formula.shiftReferences('=SUM(A1:A3)','row',1,false),'=SUM(A1:A4)');assert.equal(formula.shiftReferences('=A2','row',1,true),'=#REF!');});
test('sorting moves whole rows, styles and heights, and adjusts row formulas',()=>{const s=sheet([['Name','Qty','Total'],['Z','2','=B2*2'],['A','3','=B3*2']]);s.heights=[30,40,50];s.formats={'1:0':{bold:true}};const sorted=op.sortSheet(s,0);assert.deepEqual(Array.from(sorted.cells[1]),['A','3','=B2*2']);assert.equal(sorted.cells[2][0],'Z');assert.equal(sorted.heights[1],50);assert.equal(sorted.formats['2:0'].bold,true);assert.equal(s.cells[1][0],'Z');});
test('filters retain headers and omit hidden rows without altering data',()=>{const s=sheet([['Name'],['Alpha'],['Beta'],['ALPHABET']]);s.view={filterColumn:0,filterText:'alpha'};assert.deepEqual(Array.from(op.visibleSheetRows(s)),[0,1,3]);s.heights[1]=0;assert.deepEqual(Array.from(op.visibleSheetRows(s)),[0,3]);assert.equal(s.cells.length,4);});
test('literal replace respects case and does not interpret replacement tokens',()=>{const s=sheet([['A.b a.b']]);assert.equal(op.replaceSheetText(s,'a.b','$&',false).cells[0][0],'$& $&');assert.equal(op.replaceSheetText(s,'a.b','x',true).cells[0][0],'A.b x');});
test('sorting refuses merged data and incomplete previews',()=>{const s=sheet([['H'],['A'],['B']]);s.merges=[{r:1,er:2,c:0,ec:0}];assert.throws(()=>op.sortSheet(s,0),/Unmerge/);s.merges=[];s.previewLimited=true;assert.throws(()=>op.sortSheet(s,0),/Fully load/);});
