const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const api={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/workbookDatabaseWorkspace.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:api});
const schema={properties:{name:{type:'string'},hours:{type:'number'}},required:['name']};
const source={id:'/api/v1/assets',create:{path:'/api/v1/assets',method:'POST',schema},update:{path:'/api/v1/assets/{id}',method:'PATCH',schema}};
const sheet=()=>({cells:[['id','name','hours'],['a','Loader','10'],['b','Truck','20']],databaseSource:{path:source.id,columns:['id','name','hours'],baseline:{a:{id:'a',name:'Loader',hours:10},b:{id:'b',name:'Truck',hours:20}},mode:'update'}});
test('unchanged rows stay untouched; sorted rows preserve record identities',()=>{const s=sheet();assert.equal(api.sheetChanges(s,source).length,0);s.cells=[s.cells[0],s.cells[2],s.cells[1]];s.cells[1][2]='21';const changes=api.sheetChanges(s,source);assert.equal(changes.length,1);assert.equal(changes[0].id,'b');assert.equal(changes[0].values.hours,21);});
test('unknown IDs, duplicate IDs and structural changes cannot update records',()=>{let s=sheet();s.cells[1][0]='other';assert.throws(()=>api.sheetChanges(s,source),/unknown/);s=sheet();s.cells[2][0]='a';assert.throws(()=>api.sheetChanges(s,source),/duplicate/);s=sheet();s.cells[0][1]='other';assert.throws(()=>api.sheetChanges(s,source),/headers/);});
test('blank IDs create new records, removed rows never imply deletes',()=>{const s=sheet();s.cells.splice(2,1);assert.equal(api.sheetChanges(s,source).length,0);s.cells.push(['','New','0']);const c=api.sheetChanges(s,source)[0];assert.equal(c.id,undefined);assert.equal(c.action.method,'POST');assert.equal(c.values.hours,0);});
test('schema types and permissions reject incompatible changes',()=>{const s=sheet();s.cells[1][2]='bad';assert.throws(()=>api.sheetChanges(s,source),/valid number/);s.cells[1][2]='11';assert.throws(()=>api.sheetChanges(s,{...source,update:undefined}),/supported edit/);assert.equal(api.fieldValue('false',{type:'boolean'},{}),false);assert.equal(api.fieldValue('',{anyOf:[{type:'number'},{type:'null'}]},{}),null);assert.throws(()=>api.fieldValue('true',{type:'object'},{}),/JSON/);});
