const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:name=>load('src/lib/'+name.replace('./','')+'.ts'),Date});return exports;}
const api=load('src/lib/workbookConvenience.ts');
const sheet=()=>({id:'sheet',name:'Sheet 1',cells:[['1','a'],['3','b'],['',''],['','']],widths:[160,160],heights:[34,34,34,34],merges:[],formats:{'0:0':{bold:true}}});
test('autofill extends numeric series in one copy without mutating the source',()=>{const s=sheet(),filled=api.autofillRange(s,{r:0,c:0,er:3,ec:0},'down',true);assert.deepEqual(Array.from(filled.cells,row=>row[0]),['1','3','5','7']);assert.equal(s.cells[2][0],'');assert.equal(filled.formats['3:0'].bold,true);});
test('autofill supports ISO dates and copying right',()=>{const s=sheet();s.cells[0][0]='2026-10-01';s.cells[1][0]='2026-10-03';assert.equal(api.autofillRange(s,{r:0,c:0,er:3,ec:0},'down',true).cells[3][0],'2026-10-07');assert.equal(api.autofillRange(s,{r:0,c:0,er:0,ec:1},'right').cells[0][1],'2026-10-01');});
test('autofill rejects merged cells and invalid seeds',()=>{const s=sheet();s.merges=[{r:0,c:0,er:1,ec:0}];assert.throws(()=>api.autofillRange(s,{r:0,c:0,er:3,ec:0},'down'),/Unmerge/);s.merges=[];assert.throws(()=>api.autofillRange(s,{r:0,c:1,er:3,ec:1},'down',true),/starting numbers/);});
test('print retains blank rows and merges while escaping untrusted cell text',()=>{const s=sheet();s.cells[0][0]='<script>alert(1)</script>';s.merges=[{r:0,c:0,er:0,ec:1}];const html=api.printableSheetHtml(s,'<Workbook>');assert.ok(html.includes('colspan="2"'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));assert.equal((html.match(/<tr /g)||[]).length,4);assert.ok(html.includes('&lt;Workbook&gt;'));});
test('common values are column-specific and ranked by frequency',()=>{const s=sheet();s.cells=[['Equipment','Project'],['Rig A','Site'],['Rig A','Other'],['Rig B','Site']];assert.deepEqual(Array.from(api.commonColumnValues([], 'Equipment',s,0)),['Rig A','Rig B']);});
