const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(name){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Date,structuredClone,require:n=>load(n.replace('./',''))});return exports;}
const api=load('workbookMapping'),plain=v=>JSON.parse(JSON.stringify(v));
const sheet=cells=>({id:'s',name:'Report',cells,widths:cells[0].map(()=>120),heights:cells.map(()=>30),merges:[],formats:{}});
const base=(s,extra)=>({...api.defaultLayout(s),...extra});
test('multi-row headers, fixed metadata and exclusions extract records without blank duplicates',()=>{const s=sheet([['Project','Site A',''],['Fuel report','',''],['Equipment','Quantity',''],['Rig A','10',''],['','',''],['Total','10',''],['Rig B','20','']]);const l=base(s,{headerRows:[1,2],start:3,end:6,exclude:[5],fields:{asset:{kind:'column',r:0,c:0},quantity:{kind:'column',r:0,c:1},project:{kind:'cell',r:0,c:1}}});const out=api.extractMapping(s,l);assert.deepEqual(plain(out.rows),[['Rig A','10','Site A'],['Rig B','20','Site A']]);assert.deepEqual(plain(out.locations[1].asset),{r:6,c:0});assert.equal(s.cells[5][0],'Total');});
test('records across columns support labels down the sheet',()=>{const s=sheet([['Name','Eric','Ama'],['Hours','8','7']]);const out=api.extractMapping(s,base(s,{mode:'columns',start:1,end:2,fields:{name:{kind:'row',r:0,c:0},hours:{kind:'row',r:1,c:0}}}));assert.deepEqual(plain(out.rows),[['Eric','8'],['Ama','7']]);});
test('single form resolves merged values and calculated formulas',()=>{const s=sheet([['Name','Eric',''],['Hours','4','=B2*2']]);s.merges=[{r:0,c:1,er:0,ec:2}];const out=api.extractMapping(s,base(s,{mode:'form',start:0,end:1,fields:{name:{kind:'cell',r:0,c:2},hours:{kind:'cell',r:1,c:2}}}));assert.deepEqual(plain(out.rows),[['Eric','8']]);assert.deepEqual(plain(out.locations[0].name),{r:0,c:1});});
test('repeated job card blocks repeat relative cells and retain fixed project',()=>{const s=sheet([['Name','Eric'],['Hours','8'],['Name','Ama'],['Hours','7']]);const l=base(s,{mode:'blocks',start:0,end:3,blockSize:2,fields:{name:{kind:'block',r:0,c:1},hours:{kind:'block',r:1,c:1}}});assert.deepEqual(plain(api.extractMapping(s,l).rows),[['Eric','8'],['Ama','7']]);l.end=2;assert.throws(()=>api.extractMapping(s,l),/incomplete/);});
test('ambiguous labels require manual mapping while unique headers and form labels are suggested',()=>{const s=sheet([['Name','Name','Hours'],['Eric','Ama','8']]);const table={columns:[{name:'name'},{name:'hours'}]};const proposed=api.suggestFields(s,base(s,{}),table);assert.equal(proposed.name,undefined);assert.equal(proposed.hours.c,2);const form=sheet([['Name','Eric'],['Hours','8']]);assert.equal(api.suggestFields(form,base(form,{mode:'form',start:0,end:1}),table).hours.r,1);});
test('unsafe layouts and formula errors cannot silently pass extraction',()=>{const s=sheet([['Header',''],['=1/0','']]);const l=base(s,{fields:{value:{kind:'column',r:0,c:0}}});assert.equal(api.extractMapping(s,l).issues.length,1);assert.throws(()=>api.extractMapping(s,{...l,needsReview:true}),/structure changed/);assert.throws(()=>api.extractMapping(s,{...l,fields:{value:{kind:'cell',r:0,c:0}}}),/Single form/);assert.throws(()=>api.extractMapping(s,{...l,end:99}),/outside/);assert.throws(()=>api.parseCellAddress('B0'),/address/);assert.equal(api.cellAddress(2,99),'CV3');});
test('legacy column mappings open as equivalent layouts',()=>{const s=sheet([['Title'],['Name'],['Eric']]);s.connection={headerRow:1,mapping:{name:0}};const l=api.defaultLayout(s);assert.equal(l.start,2);assert.deepEqual(plain(api.extractMapping(s,l).rows),[['Eric']]);});

test('hidden database details apply to populated rows without changing sheet cells',()=>{const s=sheet([['Hours'],['8'],[''],['7']]);const before=JSON.stringify(s);const l=base(s,{start:1,end:3,fields:{hours:{kind:'column',r:0,c:0},project_id:{kind:'constant',r:0,c:0,value:'project-123'},employee_id:{kind:'constant',r:0,c:0,value:'employee-456'}}});assert.deepEqual(plain(api.extractMapping(s,l).rows),[['8','project-123','employee-456'],['7','project-123','employee-456']]);assert.equal(JSON.stringify(s),before);});
