const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(name){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Date,File,Blob,Uint8Array,TextEncoder,atob,btoa,crypto:require('node:crypto').webcrypto,structuredClone,require:n=>n.startsWith('./')?load(n.slice(2)):require(n)});return exports;}
const api=load('workbookMedia'),operations=load('workbookOperations'),convenience=load('workbookConvenience');
const asset={id:'a',name:'report.txt',mime:'application/octet-stream',size:3,data:'YWJj'};
const book=()=>({version:1,id:'b',name:'Book',template:false,sheets:[{id:'s',name:'Data',cells:[['Name',''],['Z',''],['A','']],widths:[160,160],heights:[34,34,34],merges:[]}]});
test('attachments stay offline in the workbook, preserve cell values and support remove/undo snapshots',()=>{const original=book(),next=api.insertMedia(original,'s',1,1,[asset]);assert.equal(next.assets.a.data,'YWJj');assert.equal(next.sheets[0].cells[1][0],'Z');assert.equal(original.assets,undefined);api.validateMedia(next);const removed=api.removeMedia(next,'s','1:1','a');assert.equal(removed.assets.a,undefined);assert.equal(next.assets.a.data,'YWJj');});
test('merged cells receive attachments at their anchor',()=>{const b=book();b.sheets[0].merges=[{r:1,c:0,er:1,ec:1}];const next=api.insertMedia(b,'s',1,1,[asset]);assert.deepEqual(Array.from(next.sheets[0].media['1:0']),['a']);});
test('sorting and autofill keep media with cell content',()=>{const b=api.insertMedia(book(),'s',1,0,[asset]),s=b.sheets[0];assert.equal(operations.sortSheet(s,0).media['2:0'][0],'a');assert.equal(convenience.autofillRange(s,{r:1,c:0,er:2,ec:0},'down').media['2:0'][0],'a');assert.equal(convenience.dragFill(s,{r:1,c:0,er:1,ec:0},{r:1,c:0,er:2,ec:0},true).media['2:0'][0],'a');});
test('folder removal moves sheets to Unfiled without deleting them',()=>{let b=api.changeFolder(book(),'f','Maintenance');b.sheets[0].folderId='f';api.validateMedia(b);assert.throws(()=>api.changeFolder(b,'other','maintenance'),/already exists/);const next=api.removeFolder(b,'f');assert.equal(next.sheets.length,1);assert.equal(next.sheets[0].folderId,undefined);assert.equal(b.sheets[0].folderId,'f');});
test('invalid attachments, references, sizes and active content are rejected',()=>{for(const mutate of [b=>b.assets.a.mime='text/html',b=>b.assets.a.data='!!!!',b=>b.assets.a.size=4,b=>b.sheets[0].media={'99:0':['a']},b=>b.sheets[0].media={'1:0':['missing']}]){const b=structuredClone(api.insertMedia(book(),'s',1,0,[asset]));mutate(b);assert.throws(()=>api.validateMedia(b));}});
test('generic files are download-only and byte limits are enforced before reading',async()=>{const a=await api.readWorkbookAsset(new File(['hello'],'page.html',{type:'text/html'}));assert.equal(a.mime,'application/octet-stream');assert.equal(atob(a.data),'hello');await assert.rejects(api.readWorkbookAsset(new File([],'empty.txt')),/nonempty/);});
test('attachment ZIP includes exact bytes and a cell manifest',async()=>{const X=require('xlsx'),blob=await api.attachmentArchive(api.insertMedia(book(),'s',1,0,[asset]));const zip=X.CFB.read(new Uint8Array(await blob.arrayBuffer()),{type:'buffer'});const found=zip.FileIndex.find(f=>f.name==='a-report.txt');assert.equal(Buffer.from(found.content).toString(),'abc');assert.ok(zip.FileIndex.some(f=>f.name==='attachments.json'));});
test('print escapes attachment names and includes supported images only',()=>{const b=api.insertMedia(book(),'s',1,0,[{...asset,name:'<script>file</script>'}]);const html=convenience.printableSheetHtml(b.sheets[0],b.name,b.assets);assert.ok(html.includes('&lt;script&gt;file'));assert.ok(!html.includes('<script>'));});
